### ISSUE TITLE
User Flow - Post Ride

### ISSUE THREAD

**Issue by neearjkukreti** [neearjkukreti/rideshareapp#4]
Logged in user must be able to post ride in system using cars attached to his/her account.

Placeholder in user dashboard screen have been already created for same.

Female passenger must be able to post rides for with female only option. This selection shouldn't be visible to male passengers.

If user don't have any car already in his account he should be shown appropriate message and link to add "Add Car". Post Ride button would be disable for him until he add at least one Car to his account.

While posting ride user will also specify number of seats he want to share. Number should be <=4 and should be a configuration in Javascript file.

Please brainstorm on possible use cases and update ticket with same.

**Comment by ghost** [comment]
issue close successfully

**Comment by neearjkukreti** [comment]
Pankaj, have you tested this issue before closing.

I doubt this component is working after latest changes to user dashboard.

I believe as now we are showing things in light-box against our earlier
approach, logic for controller is breaking. Changes need fixes to make
functionality work. Also, UI need to be aligned as per site look and feel.

On Sun, Apr 5, 2015 at 6:42 PM, pankajnegi21 notifications@github.com
wrote:

> issue close successfully
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neearjkukreti/rideshareapp/issues/4#issuecomment-89769615
> .

## 

Thanks,
Neeraj Kr. Kukreti
